# example netlify.toml
[build]
command = "yarn build"
functions = "functions"
publish = "dist"

## Uncomment to use this redirect for Single Page Applications like create-react-app.
## Not needed for static site generators.

[[redirects]]
from = "/api/*"
to = "https://smartpro.solutions/:splat"
status = 200    

## Uncomment to deploy site to a custom domain
## Make sure to add a custom domain in your Netlify site settings
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "ALLOW-FROM https://yourdomain.com"




## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
